"""Passive mitmproxy addon: harvest the game's accesstoken from a REAL session.

The official API only issues tokens to requests carrying a valid XIGNCODE cookie
(generated by the native SDK inside the genuine client) - it cannot be minted
from a script. So let the real client do its normal guest login through a MITM
proxy and save the token it legitimately receives:

    mitmdump --listen-host 0.0.0.0 -p 8888 -s api/auth/token_harvester.py

Point the device/redroid at the proxy (system CA installed), press Guest login
once; this writes repo-root captured_token.txt (+ captured_guest.json), which
api.config._autoload_token picks up for api/ranking/fetch_seasonal.py.

Read-only: every flow passes through untouched.
"""
import json
import os
import sys
from mitmproxy import http

API_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, API_DIR)
from config import decode_response  # noqa: E402

TOKEN_PATH = os.path.join(API_DIR, "..", "captured_token.txt")
STATE_PATH = os.path.join(API_DIR, "..", "captured_guest.json")
OFFICIAL_HOSTS = ("kgc-k8s-1.awesomepiece.com",)


def response(flow: http.HTTPFlow) -> None:
    if flow.request.pretty_host not in OFFICIAL_HOSTS:
        return
    if not flow.request.path.startswith("/auth"):
        return
    try:
        body = decode_response(flow.response.raw_content or b"")
    except Exception:
        return
    if not isinstance(body, dict) or not body.get("accessToken"):
        return
    token = body["accessToken"]
    state = {
        "loginId": body.get("loginId"),
        "token": token,
        "expiredAt": body.get("expiredAt"),
        "serverTime": body.get("serverTime"),
        "source": f"mitm {flow.request.path}",
    }
    with open(TOKEN_PATH, "w") as f:
        f.write(token)
    with open(STATE_PATH, "w") as f:
        json.dump(state, f, indent=1)
    print(f"[token_harvester] saved token ({state['loginId']}, "
          f"expires {state['expiredAt']}) from {flow.request.path}")
